const oneKMemGibiHours = 'Per 100,000 memory-gibibyte-hours';

// https://www.dynatrace.com/pricing/rate-card/

export const defaultRateCard = [
  {
    quoteNumber: 'default',
    startTime: '2020-01-01T00:00:00Z',
    endTime: '2050-12-31T23:59:59Z',
    currencyCode: 'USD',
    capabilities: [
      {
        key: 'FULLSTACK_MONITORING',
        name: 'Full-Stack Monitoring',
        quotedPrice: '1000',
        quotedUnitOfMeasure: oneKMemGibiHours,
        price: '0.01',
      },
      {
        key: 'INFRASTRUCTURE_MONITORING',
        name: 'Infrastructure Monitoring',
        quotedPrice: '4000',
        quotedUnitOfMeasure: 'Per 100,000 host-hours',
        price: '0.04',
      },
      {
        key: 'FOUNDATION_AND_DISCOVERY',
        name: 'Foundation & Discovery',
        quotedPrice: '1000',
        quotedUnitOfMeasure: 'Per 100,000 host-hours',
        price: '0.01',
      },
      {
        key: 'MAINFRAME_MONITORING',
        name: 'Mainframe Monitoring',
        quotedPrice: '10000',
        quotedUnitOfMeasure: 'Per 100,000 MSU-hours',
        price: '0.10',
      },
      {
        key: 'KUBERNETES_OPERATIONS',
        name: 'Kubernetes Platform Monitoring',
        quotedPrice: '200',
        quotedUnitOfMeasure: 'Per 100,000 pod-hours',
        price: '0.002',
      },
      {
        key: 'RUNTIME_VULNERABILITY_ANALYTICS',
        name: 'Runtime Vulnerability Analytics',
        quotedPrice: '225',
        quotedUnitOfMeasure: oneKMemGibiHours,
        price: '0.00225',
      },
      {
        key: 'RUNTIME_APPLICATION_PROTECTION',
        name: 'Runtime Application Protection',
        quotedPrice: '225',
        quotedUnitOfMeasure: oneKMemGibiHours,
        price: '0.00225',
      },
      {
        key: 'USER_SESSIONS',
        name: 'Real User Monitoring',
        quotedPrice: '225',
        quotedUnitOfMeasure: 'Per 100,000 sessions',
        price: '0.00225',
      },
      {
        key: 'USER_SESSION_REPLAYS',
        name: 'Real User Monitoring with Session Replay',
        quotedPrice: '450',
        quotedUnitOfMeasure: 'Per 100,000 session replay captures',
        price: '0.0045',
      },
      {
        key: 'USER_SESSION_PROPERTIES',
        name: 'Real User Monitoring Property',
        quotedPrice: '10',
        quotedUnitOfMeasure: 'Per 100,000 properties per session',
        price: '0.0001',
      },
      {
        key: 'SYNTHETIC_MONITORING_BROWSER',
        name: 'Browser Monitor or Clickpath',
        quotedPrice: '450',
        quotedUnitOfMeasure: 'Per 100,000 synthetic actions',
        price: '0.0045',
      },
      {
        key: 'SYNTHETIC_MONITORING_HTTP',
        name: 'HTTP Monitor',
        quotedPrice: '100',
        quotedUnitOfMeasure: 'Per 100,000 synthetic requests',
        price: '0.001',
      },
      {
        key: 'SYNTHETIC_MONITORING_THIRD_PARTY',
        name: 'Third-Party Synthetic API Ingestion',
        quotedPrice: '100',
        quotedUnitOfMeasure: 'Per 100,000 third-party synthetic results',
        price: '0.001',
      },
      {
        key: 'AUTOMATIONS',
        name: 'Automation Workflow',
        quotedPrice: '300',
        quotedUnitOfMeasure: 'Per 10,000 workflow-hours',
        price: '0.03',
      },
      {
        key: 'METRICS',
        name: 'Custom Metrics Classic',
        quotedPrice: '2',
        quotedUnitOfMeasure: 'Per 1000 metric data points',
        price: '0.002',
      },
      {
        key: 'LOGS',
        name: 'Log Monitoring Classic',
        quotedPrice: '1',
        quotedUnitOfMeasure: 'Per 1000 log records',
        price: '0.001',
      },
      {
        key: 'TRACES',
        name: 'Custom Traces Classic',
        quotedPrice: '1.4',
        quotedUnitOfMeasure: 'Per 1000 spans',
        price: '0.0014',
      },
      {
        key: 'EVENTS',
        name: 'Custom Events Classic',
        quotedPrice: '2',
        quotedUnitOfMeasure: 'Per 1000 custom events',
        price: '0.002',
      },
      {
        key: 'SERVERLESS',
        name: 'Serverless Functions Classic',
        quotedPrice: '4',
        quotedUnitOfMeasure: 'Per 1000 invocations',
        price: '0.004',
      },
      {
        key: 'LOG_MANAGEMENT_INGEST',
        name: 'Log Management & Analytics - Ingest & Process',
        quotedPrice: '2000',
        quotedUnitOfMeasure: 'Per 10,000 gibibytes',
        price: '0.20',
      },
      {
        key: 'LOG_MANAGEMENT_ANALYZE',
        name: 'Log Management & Analytics - Query',
        quotedPrice: '3500',
        quotedUnitOfMeasure: 'Per 1,000,000 gibibytes-scanned',
        price: '0.0035',
      },
      {
        key: 'LOG_MANAGEMENT_RETAIN',
        name: 'Log Management & Analytics - Retain',
        quotedPrice: '700',
        quotedUnitOfMeasure: 'Per 1,000,000 gibibyte-days',
        price: '0.0007',
      },
      {
        key: 'BUSINESS_EVENTS_INGEST',
        name: 'Events - Ingest & Process',
        quotedPrice: '2000',
        quotedUnitOfMeasure: 'Per 10,000 gibibytes',
        price: '0.20',
      },
      {
        key: 'BUSINESS_EVENTS_RETAIN',
        name: 'Events - Retain',
        quotedPrice: '700',
        quotedUnitOfMeasure: 'Per 1,000,000 gibibyte-days',
        price: '0.0007',
      },
      {
        key: 'BUSINESS_EVENTS_ANALYZE',
        name: 'Events - Query',
        quotedPrice: '3500',
        quotedUnitOfMeasure: 'Per 1,000,000 gibibytes-scanned',
        price: '0.0035',
      },
      {
        key: 'COMPUTE',
        name: 'AppEngine Functions - Small',
        quotedPrice: '1',
        quotedUnitOfMeasure: 'Per 1000 invocations',
        price: '0.001',
      },
    ],
  },
];
